In [2]:
import numpy as np 

In [6]:
#Create - from  Lists 
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D, type(arr2D), arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [14]:
# Creating - From Scratch 
arr1 = np.zeros((2,3), dtype="int64") # Prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) # Prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) # Prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) # Identity Matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # Range Element
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # Evenly Spaced Arrays 
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [15]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [18]:
# Operation on arrays 

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [19]:
# Slicing 
arr = np.array([1, 2, 3, 4, 5])
# [start, end, step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])


[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [27]:
# Multi_Dimentional Array

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [32]:
# Slicing in 3D-array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])
print(arr3D, arr3D.shape)

print(arr3D[0:1, 1:2, 1:2 ])

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]] (2, 3, 2)
[[[4]]]


In [34]:
# Normalization

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
